import os
from android_15_tool.lib.super_unpacker import SuperUnpacker

def create_twrp_device_tree(super_img_path, output_dir):
    """
    Creates a basic TWRP device tree structure from a super.img file.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    try:
        unpacker = SuperUnpacker(super_img_path)
        unpacker.parse()
        partitions = unpacker.metadata.get("partitions", [])
    except (RuntimeError, ValueError) as e:
        raise RuntimeError(f"Failed to analyze partition image: {e}")

    if not partitions:
        print("Warning: No partitions found in the super.img file.")

    board_config_path = os.path.join(output_dir, "BoardConfig.mk")
    with open(board_config_path, "w") as f:
        f.write("# TWRP Device Tree Generated by android_15_tool\n\n")
        f.write("DEVICE_PATH := device/vendor/codename\n\n")

        f.write("# Partitions\n")
        for partition in partitions:
            partition_name = partition["name"]
            f.write(f"TW_CUSTOM_RECOVERY_PARTITION_LST += \"/{partition_name}\"\n")

    print(f"TWRP device tree created at: {output_dir}")
