import os
import struct
from android_15_tool.lib.super_unpacker import SuperUnpacker

def create_twrp_device_tree(super_img_path, output_dir):
    """
    Creates a basic TWRP device tree structure from a super.img file.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    try:
        unpacker = SuperUnpacker(super_img_path)
        unpacker.parse()
        partitions = unpacker.metadata.get("partitions", [])
    except (RuntimeError, ValueError) as e:
        raise RuntimeError(f"Failed to analyze partition image: {e}")

    if not partitions:
        print("Warning: No partitions found in the super.img file.")

    board_config_path = os.path.join(output_dir, "BoardConfig.mk")
    with open(board_config_path, "w") as f:
        f.write("# TWRP Device Tree Generated by android_15_tool\n\n")
        f.write("DEVICE_PATH := device/vendor/codename\n\n")

        arch = _get_arch(output_dir)
        if arch:
            f.write(f"TARGET_ARCH := {arch}\n")
            f.write(f"TARGET_ARCH_VARIANT := {arch}\n")
            f.write(f"TARGET_CPU_ABI := {arch}\n")
            f.write(f"TARGET_CPU_ABI2 := \n")
            f.write(f"TARGET_CPU_VARIANT := generic\n\n")

        f.write("# Partitions\n")
        for partition in partitions:
            partition_name = partition["name"]
            f.write(f"TW_CUSTOM_RECOVERY_PARTITION_LST += \"/{partition_name}\"\n")

    print(f"TWRP device tree created at: {output_dir}")


def _get_arch(device_tree_dir):
    """
    Determines the device architecture by inspecting the kernel file.
    """
    kernel_path = os.path.join(device_tree_dir, "kernel")
    if not os.path.exists(kernel_path):
        return None

    with open(kernel_path, "rb") as f:
        kernel_magic = f.read(4)
        if kernel_magic == b"\x7fELF":
            f.seek(18)
            e_machine = struct.unpack("<H", f.read(2))[0]
            if e_machine == 0xB7:
                return "arm64"
            elif e_machine == 0x28:
                return "arm"
    return None


def generate_twrp_fstab(fstab_files, output_dir):
    """
    Parses fstab files and generates a single twrp.fstab file.
    """
    twrp_fstab_path = os.path.join(output_dir, "recovery", "root", "etc", "twrp.fstab")
    os.makedirs(os.path.dirname(twrp_fstab_path), exist_ok=True)

    with open(twrp_fstab_path, "w") as out_f:
        out_f.write("# TWRP fstab generated by android_15_tool\n\n")
        for fstab_file in fstab_files:
            with open(fstab_file, "r") as in_f:
                for line in in_f:
                    if line.strip() and not line.startswith("#"):
                        out_f.write(line)
