import os

def generate_twrp_build_script(device_tree_dir):
    """
    Generates a shell script to build a TWRP recovery image.
    """
    board_config_path = os.path.join(device_tree_dir, "BoardConfig.mk")
    if not os.path.exists(board_config_path):
        raise FileNotFoundError(f"BoardConfig.mk not found in {device_tree_dir}")

    codename = ""
    with open(board_config_path, "r") as f:
        for line in f:
            if "DEVICE_PATH :=" in line:
                codename = line.split(":=")[1].strip().split("/")[-1]
                break

    if not codename:
        raise ValueError("Could not determine device codename from BoardConfig.mk")

    build_script_path = os.path.join(device_tree_dir, "build_twrp.sh")
    with open(build_script_path, "w") as f:
        f.write("#!/bin/bash\n\n")
        f.write("set -e\n\n")
        f.write("# TWRP Build Script Generated by android_15_tool\n\n")
        f.write("export ALLOW_MISSING_DEPENDENCIES=true\n")
        f.write("export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1\n")
        f.write("export LC_ALL=C\n\n")
        f.write("mkdir -p ~/twrp\n")
        f.write("cd ~/twrp\n\n")
        f.write("repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0\n")
        f.write("repo sync\n\n")
        f.write(f"mkdir -p device/vendor/{codename}\n")
        f.write(f"cp -r {os.path.abspath(device_tree_dir)}/* device/vendor/{codename}/\n\n")
        f.write("source build/envsetup.sh\n")
        f.write(f"lunch omni_{codename}-eng\n")
        f.write("mka recoveryimage\n")

    os.chmod(build_script_path, 0o755)
    print(f"TWRP build script generated at: {build_script_path}")
